import user from "./classes/users";

export let theUsers : user[] = 
[
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user(),
    new user()
];