import User from './classes/users';

export let theUsers: User[] =
    [
        // new User(1, `All Might`, `IAmHere!`, `Toshinori`, `Yagi`, `yagitoshinori@uahigh.edu`, new Role(1, `Teacher`)),
        // new User(2, `Eraser Head`, `iwanttosleep...`, `Shota`, `Aizawa`, `aizawashota@uahigh.edu`, new Role(2, `Admin`)),
        // new User(3, `Deku`, `AllMight#1`, `Izuku`, `Midoriya`, `midoriyaizuku@uahigh.edu`, new Role(3, `Student`)),
        // new User(4, `Ground Zero`, `DieDieDieDieDie!!!!!`, `Katsuki`, `Bakugo`, `bakugokatsuki@uahigh.edu`, new Role(4, `Student`)),
        // new User(5, `Uravity`, `NeverGiveUp!`, `Ochaco`, `Uraraka`, `urarakaochaco@uahigh.edu`, new Role(5, ``)),
        // new User(6, `Ingenium `, `SupaFast!`, `Tenya`, `Iida`, `iidatenya@uahigh.edu`, new Role(6, `Student`)),
        // new User(7, `Froppy`, `RibbitRibbit?`, `Tsuyu`, `Asui`, `asuitsuyu@uahigh.edu`, new Role(7, `Student`)),
        // new User(8, `Grape Juice`, `Lovetheladies`, `Minoru`, `Mineta`, `minetaminoru@uahigh.edu`, new Role(8, `Student`)),
        // new User(9, `Creati`, `BooksMakeTheLooks`, `Momo`, `Yaoyorozu`, `@uahigh.edu`, new Role(9, `Student`)),
        // new User(10, `Tsukuyomi`, `HelloDarknessMyOldFriend`, `Fumikage`, `Tokoyami`, `@uahigh.edu`, new Role(10, `Student`)),
        // new User(11, `Chargebolt`, `1MillionVolts`, `Denki`, `Kaminari`, `@uahigh.edu`, new Role(11, `Student`)),
        // new User(12, `Red Riot`, `CrimsonRiot#1`, `Eijiro`, `Kirishima`, `@uahigh.edu`, new Role(12, `Student`)),
        // new User(13, `Shoto`, `IAmNotMyFather`, `Shoto`, `Todoroki`, `@uahigh.edu`, new Role(13, `Student`)),
        // new User(14, `Alien Queen`, `LetsGoParty!`, `Mina`, `Ashido`, `@uahigh.edu`, new Role(14, `Student`)),
        // new User(15, `Can't Stop Twinkling`, `SoFabulous`, `Yuga`, `Aoyama`, `@uahigh.edu`, new Role(15, `Student`)),
        // new User(16, `Earphone Jack`, ``, `Kyoka`, `Jiro`, `@uahigh.edu`, new Role(16, `Student`)),
        // new User(17, `Tentacole`, ``, `Mezo`, `Shoji`, `@uahigh.edu`, new Role(17, `Student`)),
        // new User(18, `Tailman`, `TheTailKnows`, `Mashirao`, `Ojiro`, `@uahigh.edu`, new Role(18, `Student`)),
        // new User(19, `Cellophane`, `elbowtape`, `Hanta`, `Sero`, `@uahigh.edu`, new Role(19, `Student`)),
        // new User(20, `Invisible Girl`, `YouCan'tSeeMe!`, `Toru`, `Hagakure`, `@uahigh.edu`, new Role(20, `Student`)),
        // new User(21, `Anima`, `AnimalsAreBetterThanHumans`, `Koji`, `Koda`, `@uahigh.edu`, new Role(21, `Student`)),
        // new User(22, `Sugarman`, `SugarSugarOhHoneyHoney`, `Rikido`, `Sato`, `@uahigh.edu`, new Role(22, `Student`)),
        // new User(23, `Present Mic`, `YEAAAAAAAAAA`, `Hizashi`, `Yamada`, `yamadahizashi@uahigh.edu`, new Role(23, `Teacher`)),
        // new User(24, `Midnight`, `NaughtyNaughty`, `Ken`, `Ishiyama`, `ishiyamaken@uahigh.edu`, new Role(24, `Teacher`)),
        // new User(25, `Cementoss`, `BestBuilder`, `Nemuri`, `Kayama`, `kayamanemuri@uahigh.edu`, new Role(25, `Teacher`)),
        // new User(26, `Endeavor`, `IWillBeatAllMight`, `Enji`, `Todoroki`, `endeavor@prohero.org`, new Role(26, `Pro Hero`)),
        // new User(27, `Gang Orca`, `KillerWhale#10`, `Kugo`, `Sakamata`, `gangorca@prohero.org`, new Role(27, `Pro Hero`)),
        // new User(28, `Mt. Lady`, `BestLadyIsMtLady`, `Yu`, `Takeyama`, `mtlady@prohero.org`, new Role(28, `Pro Hero`)),
        // new User(29, `Gran Torino`, `QuickerThanYou`, `Sorahiko`, ` `, `grantorino@prohero.org`, new Role(29, `Pro Hero`)),
        // new User(30, `Edgeshot`, `PaperThin`, `Shinya`, `Kamihara`, `edgeshot@prohero.org`, new Role(30, `Pro Hero`)),
        // new User(31, `Kamui Woods`, `WalkingForest`, `Shinji`, `Nishiya`, `kamuiwoods@prohero.org`, new Role(31, `Pro Hero`)),
        // new User(32, `Vlad King`, `KingVlad`, `Sekijiro`, `Kan`, `kansekijiro@uahigh.edu`, new Role(32, `Teacher`)),
        // new User(33, `Ms. Joke`, `AizawaLove`, `Emi`, `Fukukado`, `fukukadoemi@kahigh.edu`, new Role(33, `Teacher`)),
        // new User(34, `Recovery Girl`, `HealingKiss`, `Chiyo`, `Shuzenji`, `shuzenjichiyo@uahigh.edu`, new Role(34, `Admin`)),
        // new User(35, `Mr. Principal`, `SmarterAndBetterThanYou`, `Nezu`, ` `, `principalnezu@uahigh.edu`, new Role(35, `Admin`))
    ];